// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/";
  };
  "_index.tsx": {
    id: "_index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "_index": typeof import("./app/_index.tsx");
};